variables:
  AUDIT_AZURE_LIST:
    description: "Which alerts would you like to check for? Defaults to all Azure Rules."
    required: false
    type: array
    default:
      - azure-security-monitoring-agent-on
      - azure-security-system-update-on
      - azure-security-security-configuration-on
      - azure-security-endpoint-protection-on
      - azure-security-disk-encrpytion-on
      - azure-security-network-security-groups-on
      - azure-security-web-application-firewall-on
      - azure-security-next-generation-firewall-on
      - azure-security-vulnerability-assessment-on
      - azure-security-storage-encryption-on
      - azure-security-jit-network-access-on
      - azure-security-adaptive-application-controls-on
      - azure-security-sql-auditing-threat-detection-on
      - azure-security-sql-encryption-on
      - azure-security-security-contact-emails-set
      - azure-security-security-contact-phone-num-set
      - azure-security-send-email-alerts-on
      - azure-security-send-email-to-subscription-owners-on
      - azure-storage-secure-transfer-required-enabled
      - azure-storage-storage-encryption-blob-service-enabled
      - azure-storage-storage-encryption-enabled-for-file-service
      - azure-storage-public-access-level-set-private-for-blob-containers
      - azure-sql-auditing-on
      - azure-sql-threat-detection-on
      - azure-sql-threat-detection-types-all
      - azure-sql-send-alerts-set
      - azure-sql-email-service-co-administrators-enabled
      - azure-sql-auditing-retention-greater-than-90-days
      - azure-sql-threat-detection-retention-greater-than-90-days
      - azure-sql-active-directory-admin-configured
      - azure-sql-auditing-on
      - azure-sql-threat-detection-on
      - azure-sql-threat-detection-types-all
      - azure-sql-send-alerts-set
      - azure-sql-email-service-co-administrators-enabled
      - azure-sql-data-encryption-on
      - azure-sql-auditing-retention-greater-than-90-days
      - azure-sql-threat-detection-retention-greater-than-90-days
      - azure-monitoring-activity-log-alert-for-create-or-update-sql-server-firewall-rule
      - azure-monitoring-activity-log-alert-for-delete-sql-server-firewall-rule
      - azure-monitoring-activity-log-alert-for-update-security-policy
      - azure-key-vault-logging-for-keyvault-enabled
      - azure-monitoring-log-profile-exists
      - azure-monitoring-activity-log-retention-365-days-or-greater
      - azure-monitoring-activity-log-alert-for-create-polic-assignment
      - azure-monitoring-activity-log-alert-for-create-or-update-network-security-group
      - azure-monitoring-activity-log-alert-for-delete-network-security-group
      - azure-monitoring-activity-log-alert-for-create-or-update-network-security-group-rule
      - azure-monitoring-activity-log-alert-for-delete-network-security-group-rule
      - azure-monitoring-activity-log-alert-for-create-or-update-security-solution
      - azure-monitoring-activity-log-alert-for-delete-network-security-solution
      - azure-security-rdp-access-restricted-from-internet
      - azure-security-ssh-access-restricted-from-internet
      - azure-sql-sql-server-access-restricted-from-internet
      - azure-network-watcher-network-security-group-flow-log-retention-greater-than-90-days
      - azure-network-watcher-network-watcher-enabled
      - azure-security-vm-agent-installed
      - azure-security-os-disks-encrypted
      - azure-security-data-disks-encrypted
      - azure-key-vault-expiry-date-set-for-all-keys
      - azure-key-vault-expiry-date-set-for-all-secrets
